<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign in</name>
   <tag></tag>
   <elementGuidId>cb62d536-cb03-4ff1-9f11-827fed3f262a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.primary-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>195af8ce-ddb5-4941-ac2e-69127529e2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>93c96f75-ef26-4c9a-9b41-50a822dcfbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-btn</value>
      <webElementGuid>347744fd-8242-4c8e-b647-0c739985b2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>e494c102-2a54-47bf-a703-9de357e2074e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;rootClass&quot;]/div[@class=&quot;min-h-screen bg-white flex mainContainer justify-center items-center loginbody&quot;]/div[@class=&quot;flex-1 flex flex-col  relative   sm:px-6 lg:flex-none lg:px-15 xl:px-24 loginbody&quot;]/div[@class=&quot;mx-auto w-full max-w-sm lg:w-96 loginGrid loginMenus&quot;]/div[@class=&quot;gridContent z-10&quot;]/div[@class=&quot;mt-4&quot;]/form[@class=&quot;space-y-6 landScapeLogin&quot;]/div[@class=&quot;signinAll&quot;]/div[@class=&quot;-mt-10 ml-12&quot;]/button[@class=&quot;primary-btn&quot;]</value>
      <webElementGuid>7cde7a51-ee04-4f74-99a8-6e33012fe84d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>ca77b1ca-9017-4df4-ab5b-0cfd10a12f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/form/div/div[5]/button</value>
      <webElementGuid>9d1680cc-f016-4c77-9f7a-c1ba0a10dc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::button[1]</value>
      <webElementGuid>ae40b4dc-9db4-4505-ac44-6a4a721c7904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>3a135991-d184-40ae-854d-eda287a241f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>6b006875-7a01-47bb-97cb-6cfc86e1d033</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
